[2022-06-02 06:51:11,734] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: YFinance_Crawler_DAG.local2hdfs 2022-06-02T06:51:00.244106+00:00 [queued]>
[2022-06-02 06:51:11,766] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: YFinance_Crawler_DAG.local2hdfs 2022-06-02T06:51:00.244106+00:00 [queued]>
[2022-06-02 06:51:11,767] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 06:51:11,767] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-06-02 06:51:11,767] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 06:51:11,793] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): local2hdfs> on 2022-06-02T06:51:00.244106+00:00
[2022-06-02 06:51:11,797] {standard_task_runner.py:51} INFO - Started process 2302 to run task
[2022-06-02 06:51:11,802] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'YFinance_Crawler_DAG', 'local2hdfs', '2022-06-02T06:51:00.244106+00:00', '--job-id', '114', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Crawler.py', '--cfg-path', '/tmp/tmpiy4s6avf']
[2022-06-02 06:51:11,802] {standard_task_runner.py:76} INFO - Job 114: Subtask local2hdfs
[2022-06-02 06:51:11,912] {logging_mixin.py:103} INFO - Running <TaskInstance: YFinance_Crawler_DAG.local2hdfs 2022-06-02T06:51:00.244106+00:00 [running]> on host slave03
[2022-06-02 06:51:12,012] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=YFinance_Crawler_DAG
AIRFLOW_CTX_TASK_ID=local2hdfs
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T06:51:00.244106+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-02T06:51:00.244106+00:00
[2022-06-02 06:51:12,015] {taskinstance.py:1396} ERROR - Can not find the shared library: libhdfs3.so
See installation instructions at http://hdfs3.readthedocs.io/en/latest/install.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/airflow-2.0.0/dags/pyscripts/LocalFilesToHDFS.py", line 9, in put_all
    hdfs = HDFileSystem(host=host, port=port)
  File "/opt/airflow/current/dags/pyscripts/hdfs3/core.py", line 88, in __init__
    self.connect()
  File "/opt/airflow/current/dags/pyscripts/hdfs3/core.py", line 106, in connect
    get_lib()
  File "/opt/airflow/current/dags/pyscripts/hdfs3/core.py", line 670, in get_lib
    from .lib import _lib as l
  File "/opt/airflow/current/dags/pyscripts/hdfs3/lib.py", line 24, in <module>
    raise ImportError("Can not find the shared library: libhdfs3.so\n"
ImportError: Can not find the shared library: libhdfs3.so
See installation instructions at http://hdfs3.readthedocs.io/en/latest/install.html
[2022-06-02 06:51:12,018] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=YFinance_Crawler_DAG, task_id=local2hdfs, execution_date=20220602T065100, start_date=20220602T065111, end_date=20220602T065112
[2022-06-02 06:51:12,094] {local_task_job.py:118} INFO - Task exited with return code 1
