[2022-06-01 05:37:34,430] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.dnstarts03 2022-06-01T05:36:35.261683+00:00 [queued]>
[2022-06-01 05:37:34,463] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.dnstarts03 2022-06-01T05:36:35.261683+00:00 [queued]>
[2022-06-01 05:37:34,463] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:37:34,463] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-06-01 05:37:34,463] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:37:34,505] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): dnstarts03> on 2022-06-01T05:36:35.261683+00:00
[2022-06-01 05:37:34,508] {standard_task_runner.py:51} INFO - Started process 172 to run task
[2022-06-01 05:37:34,513] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ClusterStartUp', 'dnstarts03', '2022-06-01T05:36:35.261683+00:00', '--job-id', '83', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ClusterStartUp.py', '--cfg-path', '/tmp/tmpnkdl_ss2']
[2022-06-01 05:37:34,514] {standard_task_runner.py:76} INFO - Job 83: Subtask dnstarts03
[2022-06-01 05:37:34,654] {logging_mixin.py:103} INFO - Running <TaskInstance: ClusterStartUp.dnstarts03 2022-06-01T05:36:35.261683+00:00 [running]> on host slave03
[2022-06-01 05:37:34,792] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ClusterStartUp
AIRFLOW_CTX_TASK_ID=dnstarts03
AIRFLOW_CTX_EXECUTION_DATE=2022-06-01T05:36:35.261683+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-01T05:36:35.261683+00:00
[2022-06-01 05:37:34,792] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-06-01 05:37:34,793] {bash.py:158} INFO - Running command: $HADOOP_HOME/bin/hdfs --daemon start datanode
[2022-06-01 05:37:34,801] {bash.py:169} INFO - Output:
[2022-06-01 05:37:34,879] {bash.py:173} INFO - datanode is running as process 115.  Stop it first and ensure /opt/hadoop/current/pids/hadoop-root-datanode.pid file is empty before retry.
[2022-06-01 05:37:34,880] {bash.py:177} INFO - Command exited with return code 1
[2022-06-01 05:37:34,908] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-06-01 05:37:34,910] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=ClusterStartUp, task_id=dnstarts03, execution_date=20220601T053635, start_date=20220601T053734, end_date=20220601T053734
[2022-06-01 05:37:34,972] {local_task_job.py:118} INFO - Task exited with return code 1
