[2022-06-01 05:37:31,354] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.dnstarts01 2022-06-01T05:36:35.261683+00:00 [queued]>
[2022-06-01 05:37:31,398] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterStartUp.dnstarts01 2022-06-01T05:36:35.261683+00:00 [queued]>
[2022-06-01 05:37:31,398] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:37:31,398] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-06-01 05:37:31,398] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 05:37:31,444] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): dnstarts01> on 2022-06-01T05:36:35.261683+00:00
[2022-06-01 05:37:31,448] {standard_task_runner.py:51} INFO - Started process 19009 to run task
[2022-06-01 05:37:31,452] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ClusterStartUp', 'dnstarts01', '2022-06-01T05:36:35.261683+00:00', '--job-id', '81', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ClusterStartUp.py', '--cfg-path', '/tmp/tmp_0ntuw71']
[2022-06-01 05:37:31,452] {standard_task_runner.py:76} INFO - Job 81: Subtask dnstarts01
[2022-06-01 05:37:31,580] {logging_mixin.py:103} INFO - Running <TaskInstance: ClusterStartUp.dnstarts01 2022-06-01T05:36:35.261683+00:00 [running]> on host slave01
[2022-06-01 05:37:31,715] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ClusterStartUp
AIRFLOW_CTX_TASK_ID=dnstarts01
AIRFLOW_CTX_EXECUTION_DATE=2022-06-01T05:36:35.261683+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-01T05:36:35.261683+00:00
[2022-06-01 05:37:31,715] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-06-01 05:37:31,716] {bash.py:158} INFO - Running command: $HADOOP_HOME/bin/hdfs --daemon start datanode
[2022-06-01 05:37:31,722] {bash.py:169} INFO - Output:
[2022-06-01 05:37:31,790] {bash.py:173} INFO - datanode is running as process 14352.  Stop it first and ensure /opt/hadoop/current/pids/hadoop-root-datanode.pid file is empty before retry.
[2022-06-01 05:37:31,791] {bash.py:177} INFO - Command exited with return code 1
[2022-06-01 05:37:31,819] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-06-01 05:37:31,821] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=ClusterStartUp, task_id=dnstarts01, execution_date=20220601T053635, start_date=20220601T053731, end_date=20220601T053731
[2022-06-01 05:37:31,905] {local_task_job.py:118} INFO - Task exited with return code 1
